name: Hello World 02
on: [push]
jobs:
  Hello-World-Job02:
    runs-on: codebuild-github_Action_demo-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World 02 from the Codebuild!"
      - run: printenv
      - run: pwd
      - run: uname -r
      - run: echo "this should be executed from the Codebuild"
