name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on: codebuild-github_Action_demo-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World!"
      - run: printenv
      - run: pwd
      - run: uname -r
      - run: echo "this should be executed from the Codebuild"
