name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on: codebuild-github_Action_demo-${{ github.run_id }}-${{ github.run_attempt }}
    # Suggested in thread: https://github.com/actions/runner-images/discussions/7188#discussioncomment-6750749
    steps: 
     - run: sudo swapoff -a
     - run: sudo fallocate -l 10M /swapfile
     - run: sudo chmod 600 /swapfile
     - run: sudo mkswap /swapfile
     - run: sudo swapon /swapfile
     - run: sudo swapon --show

      # - run: curl -i https://www.google.com            
      # - run: curl -i https://api.github.com.         
      # - run: echo "Hello World!"   
      # - run: printenv. 
      # - run: pwd  
      # - run: uname -r     
      # - run: echo "this should be executed from the  Codebuild test reserve capacity fleet"
