name: Test webhook workflow
on: [push]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
  
jobs:
  deploy_dev:
    name: job01_deploy_dev
    runs-on:
      - codebuild-testWebhook-${{ github.run_id }}-${{ github.run_attempt }}
      - buildspec-override:true
    steps:
      - run: echo "Hello World 01!" 
  deploy_prod:
    name: job02_deploy_prod
    runs-on:
      - codebuild-testWebhook-${{ github.run_id }}-${{ github.run_attempt }}
      - buildspec-override:true
    steps:
      - run: echo "Hello World 02!" 

