name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-githubSwapTesting-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"
      - run: sudo swapoff -a
      - run: sudo fallocate -l 1G /swapfile
      - run: sudo chmod 600 /swapfile
      - run: sudo mkswap /swapfile
      - run: sudo swapon /swapfile
      - run: sudo swapon --show 
