name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-testWebhook-${{ github.run_id }}-${{ github.run_attempt }}
      # - image:arm-3.0
      # - instance-size:medium
      # - buildspec-override:true
    steps:
      - run: echo "Hello World!" 
      - run: echo "List all CB the environment variables!"
      - run: printenv | grep CODEBUILD
